[target.x86_64-pc-windows-gnu]
runner = ["wine"]
linker = "x86_64-w64-mingw32-gcc"
rustflags = ["-L", "lib"]

[env]
# Suppress Wine noise when running tests
WINEDEBUG = { value = "-all", force = false }
# pskernel.dll location
WINEPATH = { value = "", force = false }
